# Generated by Django 3.0.8 on 2020-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('runs', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
            ],
        ),
    ]
