# Generated by Django 3.0.8 on 2020-07-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='average',
            new_name='matches',
        ),
    ]
