# Generated by Django 3.0.8 on 2020-07-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0002_auto_20200720_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='catches',
        ),
    ]
