# Generated by Django 3.0.8 on 2020-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0003_remove_player_catches'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='notouts',
            field=models.IntegerField(default=0),
        ),
    ]
