# Generated by Django 3.0.8 on 2020-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0004_player_notouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runscored', models.IntegerField(default=0)),
                ('scoredby', models.IntegerField(default=0)),
                ('wicketby', models.IntegerField(default=0)),
                ('nameofbatsmen', models.CharField(max_length=30)),
                ('nameofbowler', models.CharField(max_length=30)),
            ],
        ),
    ]
